### ISSUE TITLE
null commitMessage on PR sync

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist-skills/pr-commit-check-skill#55]
it's started coming up with errors like "TypeError: re-find must match against a string.", and these cause the process to either hang or not report a success/failure.

**Comment by slimslenderslacks** [comment]
This null commitMessage is coming from a force Push.

**Comment by slimslenderslacks** [comment]
After a quick look, we are getting null commit messages on forced pushes from forks.  
The last one was a force push from clyfe on the "Add mandatory/all methods to RefLike protocol"
It was strange because we did call the GitHub API to mark that CheckRun as having finished neutrally (since we failed to process the check internally) and got a 200 back but apparently, the CheckRun didn't change state.
For now, I'm not even going to create the pending CheckRun if the commit message is null and then our git integration, we're making a fix for the null commit message in this scenario.

**Comment by slimslenderslacks** [comment]
cc @weavejester

**Comment by weavejester** [comment]
Thanks for checking this out.

**Comment by slimslenderslacks** [comment]
@weavejester by the way, your email is bouncing for me today (apologies for using this as a chat!)

**Comment by weavejester** [comment]
Is my email still bouncing? I'm getting emails from Github okay, but perhaps there's an issue with a specific address. Could I ask which email address you're using?

**Comment by slimslenderslacks** [comment]
@weavejester ya, it is james@booleanknot.com that is bouncing for me (just tried again now).

**Comment by weavejester** [comment]
@slimslenderslacks Thanks! It looks like some MX records have mysteriously disappeared for that domain in particular! I'm sorting it out now.

**Comment by slimslenderslacks** [comment]
@weavejester ya, that sounds right (that's what the mailer daemon was complaining about on my end for sure).

**Comment by weavejester** [comment]
Okay, it should be fixed now. I was definitely receiving email at that address before, so I can't think how all my DNS records suddenly vanished for that domain.
